### ISSUE TITLE
GroundStationLocation.horizonElevations never set

### ISSUE THREAD

**Issue by diamondo25** [davidmoten/predict4java#5]
The following array is only being copied and then a single element is read, for each iteration of `calculateObs`, called by `getPosition`, called by the main predictor code.

https://github.com/davidmoten/predict4java/blob/a6e848b4bb4a68b5fbc74107674e924cc02d5a78/src/main/java/com/github/amsacode/predict4java/GroundStationPosition.java#L50
https://github.com/davidmoten/predict4java/blob/a6e848b4bb4a68b5fbc74107674e924cc02d5a78/src/main/java/com/github/amsacode/predict4java/GroundStationPosition.java#L108-L120

https://github.com/davidmoten/predict4java/blob/a6e848b4bb4a68b5fbc74107674e924cc02d5a78/src/main/java/com/github/amsacode/predict4java/AbstractSatellite.java#L550-L557

**Comment by davidmoten** [comment]
Thanks! I'll have a look.

**Comment by davidmoten** [comment]
Fixed now @diamondo25, thanks for raising it. I've deployed 1.3 to Maven Central under a different groupId (`com.github.davidmoten`).

**Comment by diamondo25** [comment]
Thanks for the modification, but this doesn't really solve the actual issue: you cannot set the HorizonElevations! Its a private field inside the GroundStationPosition class.
Also, adding a function to get the elevation for the specific degree instead of copying the array everytime and getting a single entry would make it a bit faster.

**Comment by davidmoten** [comment]
ah, thanks. good suggestion about the accessor. Would be nice if decisions like that were jmh benchmark driven eh.

**Comment by davidmoten** [comment]
Would you like to make a PR for this issue?

**Comment by diamondo25** [comment]
I'm currently unable to do the modifications.

**Comment by davidmoten** [comment]
No worries, I'll sort it

**Comment by davidmoten** [comment]
fix deployed to Maven Central as version com.github.davidmoten:predict4java:1.3.1
